### ISSUE TITLE
Privacy Error for Developer List link 

### ISSUE THREAD

**Issue by tylorr** [glfw/website#22]
On the http://www.glfw.org/ website at the bottom left is a link labeled "Developer List" which leads to this link: https://lists.stacken.kth.se/mailman/listinfo/glfw-dev. When I try to go to that link Chrome shows me a Privacy Error saying:

> Your connection is not private
> 
> ... When Chrome tried to connect to lists.stacken.kth.se this time, the website sent back unusual and incorrect credentials...

**Comment by siavashserver** [comment]
Same issue on Firefox, Chromium and QupZilla.

@elmindreda Most of the fun is happening at github and sf.net forum; may be it's time to retire the mailing list :)

**Comment by elmindreda** [comment]
Yes, retired or moved and reinvigorated. It's currently hosted by my old computer club because that made sense back in 2005. The cert itself is fine, only you need to get the club's root cert from [AFS](https://en.wikipedia.org/wiki/Andrew_File_System) and manually assign trust to it, which isn't reasonable to expect in this context.

**Comment by siavashserver** [comment]
Somehow addressed by addc0cd940a3f6e1ffd31d278e940bbe1a8b0967 :)
